#!/data/data/com.termux/files/usr/bin/bash
echo "--------------"
echo "aps postinst"
echo "Termux: $TERMUX_VERSION"
echo
echo "Verifying if root permissions is available"

if su -c true >/dev/null 2>&1; then
	echo "[ OK ] Root granted, not exiting"
else
	echo "[ FAILED! ] Root not granted. Please ensure you have root access on your Android device, as APS will not function without it."
	exit 1
fi

